# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VFSsimple-Drv-Rsync
version:      0.02
version_from: lib/VFSsimple/Drv/Rsync.pm
installdirs:  site
requires:
    VFSsimple::Base:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
